### ISSUE TITLE
iSpindel new firmware

### ISSUE THREAD

**Issue by MatthBou** [thorrak/brewflasher#13]
Hi @thorrak ,

A new firmware version is available for the iSpindel (7.1.4).
Is it possible to update  Brewflasher?

Thank's a lot!!!!

**Comment by thorrak** [comment]
Done

**Comment by MatthBou** [comment]
Thank's!!

**Comment by MatthBou** [comment]
A new firmware version is available for the iSpindel (7.2.1).
Is it possible to update Brewflasher?

Thank's a lot!!!!

**Comment by thorrak** [comment]
Sure thing - done

**Comment by MatthBou** [comment]
many thank's

**Comment by MatthBou** [comment]
Hello,
A new firmware version is available for the iSpindel (7.3.3).
Is it possible to update Brewflasher?

Thank you in advance!
