### ISSUE TITLE
Windows Defender flags brewflasher as malware

### ISSUE THREAD

**Issue by mp-se** [thorrak/brewflasher#15]
Apologies for the message in swedish. 

But windows defender flags the latest release as Trojan:Script/Wacthac.B!ml and blocks the download. Probably an issue connected to compiled python programs. I found this link that might help to fix it, https://medium.com/@markhank/how-to-stop-your-python-programs-being-seen-as-malware-bfd7eb407a7

I can assist in testing but dont have a dev environmetnt setup for this yet (and probably defender will block it)

![image](https://user-images.githubusercontent.com/51722613/149616962-365d2eb8-7b19-43ee-9acd-a2ab3592adad.png)

**Comment by lbussy** [comment]
WIndows 11 here.  I get an initial "Windows blocked this program," and when I click "more info" I am allowed to "run anyway."

**Comment by mp-se** [comment]
Im using det windows 10 with latest insider edition

**Comment by uSlackr** [comment]
This is normal for software that isn’t well known. It’s simply a reputation score. If enough people download tires and use it, Defender will eventually catch up.

\\\\ Greg
________________________________

**Comment by mp-se** [comment]
Dont think thats the case, then i would have the option to continue like lbussy did.

**Comment by thorrak** [comment]
Let's try something. I just rebuilt BrewFlasher for Windows and reattached the new version to the [release](https://github.com/thorrak/brewflasher/releases/tag/v1.2.0). Let me know if that works.

If it does... I'll come back here and admit what I did wrong last time before I close this issue. If it doesn't work, then we can rule out [recompiling the bootloader](https://stackoverflow.com/questions/53584395/how-to-recompile-the-bootloader-of-pyinstaller) as a fix. ;)

**Comment by mp-se** [comment]
On my machine it still flags as malware, i uploaded the new file to virustotal.com and microsoft and clamav gives a false positive on the file.

**Comment by thorrak** [comment]
> On my machine it still flags as malware, i uploaded the new file to virustotal.com and microsoft and clamav gives a false positive on the file. You can upload and test it there befor publishing.

Alrighty. I’ll get it submitted to Microsoft as a false positive after lunch.

**Comment by thorrak** [comment]
Submitted. And now we wait. :)

**Comment by thorrak** [comment]
It should now be properly tagged: 

<img width="1111" alt="Screen Shot 2022-01-15 at 4 25 01 PM" src="https://user-images.githubusercontent.com/2457900/149638197-0dc1db18-e437-459e-9535-411d460f5a37.png">

**Comment by mp-se** [comment]
Windows is no longer blocking the file so that part worked. However the program does not start properly on my machine. The older versions works fine. I will check on some of the other computers tomorrow. I regard this issue as closed.

**Comment by thegreatgunbantoad** [comment]
Running fine under Win11 insider build 220107-2122.  Downloading the file in Chrome 97.0.4692.71 gives a warning that the file is not commonly downloaded, but it does let you download it.

**Comment by thorrak** [comment]
> Running fine under Win11 insider build 220107-2122. Downloading the file in Chrome 97.0.4692.71 gives a warning that the file is not commonly downloaded, but it does let you download it.

I mean... that just means that more people need to download it. 🙃
