### ISSUE TITLE
Support for BrewUNO

### ISSUE THREAD

**Issue by perlporter** [thorrak/brewflasher#16]
First of all congratulations for the excellent work.

I would like to request that the BrewUNO project be added to the list of supported firmware.

https://github.com/uncodead/BrewUNO

**Comment by thorrak** [comment]
Any time!

**Comment by uncodead** [comment]
Hey @thorrak! How are you?

Do you know the brewuno project? We use two binaries to install (firmware and spiffs). 

We can talk to make an installation available in your project.

**Comment by thorrak** [comment]
Hey there! Admittedly, I wasn't familiar with it before @perlporter mentioned it, but it looks like a really useful project!

In looking at it again, I think I made a mistake earlier -- I thought you didn't distribute precompiled binaries as I didn't see any in the release, but in looking at it again, I now see that you have them in the [bin/ directory of your repo](https://github.com/uncodead/BrewUNO/tree/master/bin). Is it OK if I set up BrewFlasher to flash those binaries?

**Comment by uncodead** [comment]
Sure! You can grab the latest version from the bin folder and make the installation available in your project! Any questions, call me!

**Comment by thorrak** [comment]
> Sure! You can grab the latest version from the bin folder and make the installation available in your project! Any questions, call me!

Done!

https://web.brewflasher.com/fw/77/

Also available via the BrewFlasher client.

**Comment by dumpamob** [comment]
Could you update this project's binaries and always use the latest release? Thanks.

https://github.com/uncodead/BrewUNO/releases
