### ISSUE TITLE
TiltBridge - BETA - D32_PRO_TFT-v1.1.1-Beta - TFT not downloading

### ISSUE THREAD

**Issue by x2harry** [thorrak/brewflasher#19]
Hello
I keep getting the below error when trying to update my tiltbridge , have tried over a couple of days.
TiltBridge - BETA - D32_PRO_TFT-v1.1.1-Beta - TFT
Error downloading SPIFFS/LittleFS file! 
Cheers

**Comment by thorrak** [comment]
Why are you using the 1.1.1 beta rather than the fully-released v1.1.1. Does that one also not work?

**Comment by x2harry** [comment]
Hi
Tried the fully-released v1.1.1-TFT, sorry did not know this was for the D32_Pro.
This downloaded to the ESP32 but just get a white screen and no " SSID
TiltBridgeAP" shows on the network.

**Comment by thorrak** [comment]
I've tested this on my end, and it appears to be working both in BrewFlasher 1.5.0 and the upcoming 1.5.1. Closing this issue for now -- if you experience it in the future, please feel free to reopen it.
