### ISSUE TITLE
Ispindel firmware flash not appearing to work

### ISSUE THREAD

**Issue by jesselll** [thorrak/brewflasher#20]
Hi there, 

I've flashed my Ispindel using the latest available firmware on brewflasher. It appeared to work as expected, however the SSID of the device is ESP-6229.. instead of the expected iSpindel.. 

Wondering if you can help. thanks

**Comment by thorrak** [comment]
I checked, and brewflasher is set to flash the current (7.2.1) version of the iSpindel firmware, so if you're running into issues it's unlikely to be brewflasher-related in this case. I would reach out to someone more familiar with the iSpindel project to see if something may have changed.

**Comment by reddishtg** [comment]
@jesselll Hate to bump a closed thread, but did you find a resolution to this?  I'm not seeing anything through the iSpindel issues or anywhere else online and could use some help finding the right solution here.
