### ISSUE TITLE
Add support for ESP32C3 mini boards

### ISSUE THREAD

**Issue by mp-se** [thorrak/brewflasher#23]
Can you add support for ESP32C3 mini board, just ported my GravityMon software to that board and it looks like it was not supported by brewflasher.

**Comment by thorrak** [comment]
Probably -- let me take a look

**Comment by mp-se** [comment]
I think something is missing, on web.brewflasher.com I get the error "Failed to download manifest" 

On the command line version this output (using the master branch): 
```
Verifying firmware list is up-to-date before downloading...
Downloading firmware...
Downloading partitions file...
Downloading bootloader file...
Downloading otadata file...
Downloading main firmware file...
Downloaded successfully!
Error - unsupported device family. Try updating BrewFlasher.
```

**Comment by thorrak** [comment]
I think that https://github.com/thorrak/brewflasher/commit/eac21bd64c2e06da07ffbbee428be591a659822a should be what is required for C3 support. If you can test from the source (just run Main.py) and let me know if that works, I would appreciate it. If not, I'm happy to build binaries for whatever platform you'd like.

**Comment by mp-se** [comment]
I did the same changes myself and it flashes correctly but will not boot. From what i have concluded the c3 needs a first idf bootloader at 0x0 and i have not figured out how that is flashed from platformio and where i can find that binary. Will continue to dig into this tomorrow.

**Comment by thorrak** [comment]
I think I see it:
```
                "upload.bootloader_offset",
                "0x0" if mcu in ("esp32c3", "esp32s3") else "0x1000",
``` 
From here: https://github.com/platformio/platform-espressif32/blob/03254d41cb8e63e9b37d7c796ad55f2c00869ea5/builder/frameworks/espidf.py#L1355

**Comment by mp-se** [comment]
Tried that one but it still will not boot correctly (now it just reboots, so I see that as a small success). 

I even took the binaries from my build library to see if there was a missmatch with the bootloader binary downloaded by brewflasher, but no success. 

I think I read somewhere that the Esp32c3 has a two stage bootloader, one idf and one arduino. Dont know if they are combined into the same binary when compiled. One possibility could be not to erase the whole chip but leave the first part as is... but I want to understand how this works before trying to use workarounds.

**Comment by mp-se** [comment]
Looks like there is a need for an new bootloader for this chip. Once I replaced the downloaded bootloader.bin and ran the esptool manually the chip booted.

[bootloader.zip](https://github.com/thorrak/brewflasher/files/9818239/bootloader.zip)

This was the commandline that was used:

```
esptool.py --port COM6 --chip esp32c3 --baud 115200 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 80m 0x10000 C:\dev\brewflasher\firmware.bin 0x8000 C:\dev\brewflasher\partitions.bin 0x0 C:\dev\brewflasher\bootloader.bin 0xe000 C:\dev\brewflasher\otadata.bin --erase-all -fs detect

```

**Comment by thorrak** [comment]
I think I see what may be the cause. If I try to compile/flash a project for C3 using platformio, the flash command it executes is this:

```
"/Users/jbeeler/.platformio/penv/bin/python" "/Users/jbeeler/.platformio/packages/tool-esptoolpy/esptool.py" --chip esp32c3 --port "/dev/cu.Bluetooth-Incoming-Port" --baud 460800 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 80m --flash_size 4MB 0x0000 /Users/jbeeler/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32c3/bin/bootloader_qio_80m.bin 0x8000 /Users/jbeeler/VSCodeProjects/brewpi-esp8266/.pio/build/esp32_c3_wifi/partitions.bin 0xe000 /Users/jbeeler/.platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin 0x10000 .pio/build/esp32_c3_wifi/firmware.bin
```

...where it looks like it's using the `qio` bootloader rather than the `dio` bootloader I had selected previously. We're not specifying flash mode, unfortunately, so we're getting stuck with the default. 

All of the bootloaders should be available [here](https://github.com/thorrak/brewflasher_bins/tree/main/esp32c3) - it's just a matter of selecting the correct one.

**Comment by thorrak** [comment]
Should have specified - I've gone ahead and made the change in BrewFlasher to use the `qio` bootloader. You'll need to restart BrewFlasher to get it to download the updated device family list, but if you can give it a try and let me know, we should be in business.

**Comment by mp-se** [comment]
Looks like that solved the issues, the flashing works and it boot into my software. Good work!

**Comment by thorrak** [comment]
Perfect! I'll start prepping a release.

**Comment by thorrak** [comment]
The release should now be live. If you have a second and can check if the released windows binary works for ESP32-C3 I’d appreciate it!

**Comment by mp-se** [comment]
I was able to burn a chip and can confirm it works fine. Will do some more testing but I think we can close this one now.

**Comment by thorrak** [comment]
Awesome, thank you for your help!
