### ISSUE TITLE
Bootloader for c3 chip is faulty and firmware does not start

### ISSUE THREAD

**Issue by mp-se** [thorrak/brewflasher#34]
The bootloader for the C3 chip is faulty and the firmware does not start after flashing (reboot loop). 

Replace the bootloader with the included file that is confirmed to work.

[bootloader_c3.zip](https://github.com/thorrak/brewflasher/files/13498716/bootloader_c3.zip)

**Comment by thorrak** [comment]
Doh! Thanks for this -- I've updated the bootloader for the ESP32-C3 to the one you provided. If you relaunch BrewFlasher it should now pick up the new one.

Let me know if everything works!

**Comment by mp-se** [comment]
I confirm that flashing the C3 chip works fine now, closing this ticket. Thanks!

**Comment by thorrak** [comment]
No - thank you! Not sure why I can’t get working bootloaders to compile using Espressif’s instructions, but I appreciate you tracking them down!

**Comment by mp-se** [comment]
I know I tested it when you added support for the C3 a while back and it worked then so I dont really know why it's not working anymore. Do you know if the bootloader changes with IDF or Arduino version? I have not dug into how those things work.....
