### ISSUE TITLE
How do you set the Tilt Color with Brewflasher Repeater ?

### ISSUE THREAD

**Issue by thorrak** [thorrak/brewflasher#37]
How do you set the Tilt Color with Brewflasher Repeater ?

_Originally posted by @Nakita2k in https://github.com/thorrak/brewflasher/issues/30#issuecomment-1884929872_

**Comment by thorrak** [comment]
@Nakita2k - Which firmware are you referring to?

**Comment by Nakita2k** [comment]
Brewflasher Windows  1.7.1   https://github.com/thorrak/brewflasher/releases/download/v1.7.0/BrewFlasher-1.7.0.Windows.x64.zip
Firmware Tilt Repeater 0.1.0

**Comment by thorrak** [comment]
The tilt repeater is someone else’s firmware, so I can’t provide much guidance, other than to say that my understanding is that it just repeats the colors that are in range. If a red tilt is in range, it should be repeated.

**Comment by Nakita2k** [comment]
So there is no actual esp32 Tilt repeater firmware that works anymore. 
Okay thank you for you help.

**Comment by thorrak** [comment]
Closing this issue for now as the repeater firmware seems to work for me.
