### ISSUE TITLE
Does BrewFlasher support the latest Heltec ESP32 Wifi kits?

### ISSUE THREAD

**Issue by fkroepfl** [thorrak/brewflasher#42]
According to the TiltBridge documentation, a Heltec ESP32 WiFi kit was purchased.

- https://tiltbridge.readthedocs.io/en/master/hardware.html#heltec-style-esp32-oled-board

As can be seen on the Heltc homepage, the V3 is currently being sold.

- https://heltec.org/project/wifi-kit32-v3/

When trying to flash the TiltBridge firmware, the following error message appears.

Note: Changing the speed does not change anything. The USB cables used are data cables.
 

```
Check the firmware list before the download starts...
Downloading firmware...
Downloading partitions file...
Downloading SPIFFS/LittleFS file...
Downloading bootloader file...
Downloading otadata file...
Downloading main firmware file...
Download abgeschlossen!

Esptool command: esptool.py --port /dev/cu.usbserial-0001 --chip esp32 --baud 115200 --before default_reset --after hard_reset write_flash 0x10000 /private/var/folders/bd/tdd902m93mgckswr83knj_l40000gn/T/firmware.bin 0x8000 /private/var/folders/bd/tdd902m93mgckswr83knj_l40000gn/T/partitions.bin 0x1000 /private/var/folders/bd/tdd902m93mgckswr83knj_l40000gn/T/bootloader.bin 0x330000 /private/var/folders/bd/tdd902m93mgckswr83knj_l40000gn/T/spiffs.bin 0xe000 /private/var/folders/bd/tdd902m93mgckswr83knj_l40000gn/T/otadata.bin --erase-all -fs detect

esptool.py v4.7.0
Serial port /dev/cu.usbserial-0001
Connecting....
Firmware flash failed. esptool reports an error.

Try the flash again, or flash at a slower speed.

```

**Comment by thorrak** [comment]
Yes, **BrewFlasher** supports the Heltec ESP32 WiFi kits -- but I doubt that means what you would hope to hear. 

Unfortunately, the WiFi Kit v3 is based on the ESP32-S3 which is a completely different processor than the "base" ESP32. While the ESP32-S3 is the closest thing to a direct successor to the ESP32, library compatibility is not the same, and the ESP32-S3 allows board manufacturers to be remove the dedicated USB-to-UART chip which presents some additional quirks when trying to flash for the first time. Only projects that target the ESP32-S3 (currently just Kegmon and Gravitymon in BrewFlasher) can be used with this board.

**Comment by thorrak** [comment]
I should have mentioned, a full comparison is available from Espressif here:

https://docs.espressif.com/projects/esp-idf/en/v5.0/esp32s3/hw-reference/chip-series-comparison.html

The fact that they chose to use the "ESP32" naming convention for everything is one of the more frustrating things they've done in recent years!

**Comment by fkroepfl** [comment]
Thank you very much for the explanations. 
In fact, I could have mentioned the abbreviation "V3" in the subject line 😉
It looks like I haven't made the best choice so far when buying my ESP32 OLED boards for TiltBridge. 🤔
