### ISSUE TITLE
Release image availability is opaque

### ISSUE THREAD

**Issue by joshuascheid** [thorrak/brewflasher#44]
Perhaps just more to document.  Where does the set of available releases for a device come from?  I dug into the source an bit and there's some reference to brewflasher.com, but there's nothing public on that site listing hosted releases.

For example, there's a new 2.0.1 release for GravityMon [https://github.com/mp-se/gravitymon/releases/tag/v2.0.1], but that's not available from a dropdown list.  Updated daily, perhaps?

I went looking for an option to use local files, but did not find one.

**Comment by thorrak** [comment]
You're correct - the list of available releases is loaded from brewflasher.com, where it is maintained behind the scenes by a handful of people (mostly individual project owners). In the case of GravityMon, the author @mp-se is actually the one that maintains it. Normally he's pretty good about keeping the BrewFlasher entries up to date, but as this is a new release he may have not had a chance to update it yet.

Behind the scenes there is the ability for project authors to set up GitHub webhooks that will automatically toggle an update to BrewFlasher, but again - that's dependent on the author setting it up. (Which - @mp-se - if you want to set it up, let me know!) There is _not_ any kind of automated polling of GitHub to see if a new release of a project has been posted. 

You are correct that there is no option to use local files to flash within BrewFlasher. There are a number of alternative applications that provide that, but which do so at the cost of requiring users to properly specify each component of the firmware, where to flash, flashing options, etc. The promise of BrewFlasher is the removal of that complexity -- but that only works as a result of the curated firmware list on BrewFlasher.com.

**Comment by mp-se** [comment]
We all have different approaches to how to handle releases, in my case I only place releases on Brewflasher that has been thoroughly tested which means that I do at least one brew with the firmware. So it can take a while before its updated and in sync with github. 

I relay on brewflasher for the initial installation of the software since that can be quite difficult to handle. But since GravityMon has a firmware update feature built in that is what most people use when doing updates.

**Comment by joshuascheid** [comment]
Thanks for both of your responses and I really appreciate both of your projects and the work you put into them.  Up to you @thorrak if you want to add a little bit of doc/support on how you compile your available releases.
