### ISSUE TITLE
Sorry, but I'm stupid

### ISSUE THREAD

**Issue by kall3** [thorrak/brewflasher#8]
How do I build brewflasher on mac?

**Comment by thorrak** [comment]
Are you really looking to re-build it, launch it from source, or just to be able to use it?

If all you want to do is use it, just use the codesigned release available [here](https://github.com/thorrak/brewflasher/releases/download/v1.0.1/BrewFlasher-1.0.1.MacOS.zip).

If you want to be able to run it from source, install the requirements into your python environment and then run [Main.py](https://github.com/thorrak/brewflasher/blob/master/Main.py) as an application.

If you really want to _rebuild_ it, you're going to need to install [pyinstaller](https://www.pyinstaller.org/), install python, and use the [build.sh](https://github.com/thorrak/brewflasher/blob/master/build.sh) script - then codesign it. For obvious reasons the keys used for codesigning aren't publically available, so you won't be able to generate a true, distributable app without re-signing it yourself, but if you have changes you'd like to see, just submit a PR and I'll try to get them merged into the next signed version I release.

**Comment by kall3** [comment]
Thank you! Just wanted to use it

**Comment by kall3** [comment]
Any tips on why I can't see my ESP32 in the brewflasher software? It just tries over bluetooth. When I go into a system report I find it under USB as a uART bridge controller

**Comment by thorrak** [comment]
Was it plugged in when you launched BrewFlasher? You may need to click the "refresh" button to the right of the list of serial ports.

**Comment by kall3** [comment]
Thank you!

**Comment by thorrak** [comment]
Any time!

**Comment by kall3** [comment]
Any idea why it is stopping at "connecting"?

**Comment by thorrak** [comment]
It really depends on the device you're flashing, unfortunately. I would check the following:

- Make sure the right device is available/selected in BrewFlasher
- Check that the USB cable that you're using is a true "data" cable (this happens to a lot of people!)
- Check if your device needs to have a physical "flash" button pushed/held down before/during flashing in order to enable the flashing mode
